apiVersion: v1
kind: Config
clusters:
- cluster:
  certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUN... # base64 encoded cert
  server: https://kubernetes.example.com:6443
  name: my-cluster
- cluster:
  certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUN... # base64 encoded cert
  server: https://dev.example.com:6443
  name: my-dev-cluster
contexts:
- context:
  cluster: my-cluster
  user: my-user
  name: my-context
- context:
  cluster: my-dev-cluster
  user: my-user
  name: my-context
current-context: my-context
users:
- name: my-user
  user:
  client-certificate-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUN... # base64 encoded cert
  client-key-data: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFcA... # base64 encoded key